import networkx as nx
import scipy as sc
import matplotlib.pyplot as plt
from Subgraphs import f as f, star as s, Path as p, h as h, cycle as c

g = nx.Graph()
g.add_edge(0, 1)
f = open('../graphlets/G' + str(0) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(2, 1)
f = open('../graphlets/G' + str(1) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.complete_graph(3)
f = open('../graphlets/G' + str(2) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(2, 1)
g.add_edge(2, 3)
f = open('../graphlets/G' + str(3) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(2, 1)
g.add_edge(1, 3)
f = open('../graphlets/G' + str(4) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()

g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
f = open('../graphlets/G' + str(5) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.complete_graph(3)
g.add_edge(0, 3)
f = open('../graphlets/G' + str(6) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 2)
f = open('../graphlets/G' + str(7) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.complete_graph(4)
f = open('../graphlets/G' + str(8) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_path([0, 1, 2, 3, 4])
f = open('../graphlets/G' + str(9) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_path([0, 1, 2, 3])
g.add_edge(4, 1)
f = open('../graphlets/G' + str(10) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(0, 2)
g.add_edge(0, 3)
g.add_edge(0, 4)
f = open('../graphlets/G' + str(11) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.complete_graph(3)
g.add_edge(0, 3)
g.add_edge(1, 4)
f = open('../graphlets/G' + str(12) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.complete_graph(3)
g.add_edge(0, 3)
g.add_edge(4, 3)
f = open('../graphlets/G' + str(13) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.complete_graph(3)
g.add_edge(0, 3)
g.add_edge(0, 4)
f = open('../graphlets/G' + str(14) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3, 4])
f = open('../graphlets/G' + str(15) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
f = open('../graphlets/G' + str(16) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
g.add_edge(0, 2)
f = open('../graphlets/G' + str(17) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2])
g.add_cycle([0, 3, 4])
f = open('../graphlets/G' + str(18) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()

g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
g.add_edge(1, 3)
f = open('../graphlets/G' + str(19) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()

g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
g.add_edge(2, 4)
f = open('../graphlets/G' + str(20) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_cycle([0, 1, 4])
f = open('../graphlets/G' + str(21) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_cycle([0, 2, 5])
f = open('../graphlets/G' + str(22) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.complete_graph(4)
g.add_edge(0, 4)
f = open('../graphlets/G' + str(23) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3, 4])
g.add_edge(0, 3)
g.add_edge(1, 3)
f = open('../graphlets/G' + str(24) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
g.add_edge(1, 4)
g.add_edge(2, 4)
f = open('../graphlets/G' + str(25) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_cycle([0, 2, 4])
g.add_edge(4, 3)
f = open('../graphlets/G' + str(26) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
g.add_edge(1, 4)
g.add_edge(2, 4)
g.add_edge(3, 4)
f = open('../graphlets/G' + str(27) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_cycle([0, 2, 4])
g.add_edge(3, 4)
g.add_edge(1, 3)
f = open('../graphlets/G' + str(28) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()
g = nx.complete_graph(5)
f = open('../graphlets/G' + str(29) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
# nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
# plt.draw()
# plt.show()