import networkx as nx
import matplotlib.pyplot as plt
from Subgraphs import *
g = nx.complete_graph(5)

g_size = len(g.nodes)

# c.count_cycles(graph, cycle_size, graph_size)
c3 = cycle.count_cycles(g, 3, g_size)
c4 = cycle.count_cycles(g, 4, g_size)
c6 = cycle.count_cycles(g, 6, g_size)
c8 = cycle.count_cycles(g, 8, g_size)
# p.path_count(graph, maximum_path_length)
paths = Path.path_count(g, 6)
# ff.count_f(graph, graph_size)
ff = f.count_f(g, g_size)
# hh.count_h(graph, graph_size)
hh = h.count_h(g, g_size)
# ss.count_star(graph, star_size)
s1_3 = star.count_star(g, 3)
s1_4 = star.count_star(g, 4)
# dd.count_d(graph, graph_size)
dd = d.count_d(g, g_size)
# ww.count_w(graph, graph_size)
ww = w.count_w(g, g_size)

# graphlets
graphlets = []
graphlets.append(g17.count_g17(g))
graphlets.append(g18.count_g18(g))
graphlets.append(g19.count_g19(g))
graphlets.append(g20.count_g20(g))
graphlets.append(g21.count_g21(g))
graphlets.append(g22.count_g22(g))
graphlets.append(g23.count_g23(g))
graphlets.append(g24.count_g24(g))
graphlets.append(g25.count_g25(g))
graphlets.append(g26.count_g26(g))
graphlets.append(g27.count_g27(g))
graphlets.append(g28.count_g28(g))
graphlets.append(g29.count_g29(g))


print("C3: ", c3)
print("C4: ", c4)
print("C6: ", c6)
print("C8: ", c8)
print("Paths: ", paths)
print("F: ", ff)
print("H: ", hh)
print("S1,3: ", s1_3)
print("S1,4: ", s1_4)
print("D: ", dd)
print("W: ", ww)
print("Graphlets 17...29: ")
print(graphlets)
nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
plt.draw()
plt.show()
