import networkx as nx

g = nx.Graph()
g.add_edge(0, 1)
f = open('data2/G' + str(0) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(2, 1)
f = open('data2/G' + str(1) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2])
f = open('data2/G' + str(2) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(2, 1)
g.add_edge(2, 3)
f = open('data2/G' + str(3) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(0, 2)
g.add_edge(0, 3)
f = open('data2/G' + str(4) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
f = open('data2/G' + str(5) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2])
g.add_edge(0, 3)
f = open('data2/G' + str(6) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 2)
f = open('data2/G' + str(7) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2])
g.add_edge(3, 1)
g.add_edge(3, 2)
g.add_edge(3, 0)
f = open('data2/G' + str(8) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(2, 1)
g.add_edge(2, 3)
g.add_edge(4, 3)
f = open('data2/G' + str(9) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(2, 1)
g.add_edge(0, 3)
g.add_edge(0, 4)
f = open('data2/G' + str(10) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_edge(0, 1)
g.add_edge(0, 2)
g.add_edge(0, 3)
g.add_edge(0, 4)
f = open('data2/G' + str(11) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2])
g.add_edge(0, 4)
g.add_edge(1, 3)
f = open('data2/G' + str(12) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2])
g.add_edge(0, 3)
g.add_edge(4, 3)
f = open('data2/G' + str(13) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2])
g.add_edge(0, 3)
g.add_edge(4, 0)
f = open('data2/G' + str(14) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3, 4])
f = open('data2/G' + str(15) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
f = open('data2/G' + str(16) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
g.add_edge(0, 2)
f = open('data2/G' + str(17) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2])
g.add_cycle([0, 3, 4])
f = open('data2/G' + str(18) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(1, 4)
g.add_edge(0, 2)
f = open('data2/G' + str(19) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
g.add_edge(4, 2)
f = open('data2/G' + str(20) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
g.add_edge(1, 4)
f = open('data2/G' + str(21) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(0, 4)
g.add_edge(4, 2)
g.add_edge(0, 2)
f = open('data2/G' + str(22) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2])
g.add_edge(3, 1)
g.add_edge(3, 2)
g.add_edge(3, 0)
g.add_edge(4, 0)
f = open('data2/G' + str(23) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3, 4])
g.add_edge(0, 2)
g.add_edge(0, 3)
f = open('data2/G' + str(24) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(4, 0)
g.add_edge(4, 1)
g.add_edge(4, 2)
f = open('data2/G' + str(25) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(4, 0)
g.add_edge(4, 1)
g.add_edge(4, 2)
g.add_edge(0, 2)
f = open('data2/G' + str(26) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(4, 0)
g.add_edge(4, 1)
g.add_edge(4, 2)
g.add_edge(4, 3)
f = open('data2/G' + str(27) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.Graph()
g.add_cycle([0, 1, 2, 3])
g.add_edge(4, 0)
g.add_edge(4, 1)
g.add_edge(4, 2)
g.add_edge(0, 2)
g.add_edge(1, 3)
f = open('data2/G' + str(28) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
g = nx.complete_graph(5)
f = open('data2/G' + str(29) + '.txt', 'w')
f.write(str(nx.to_numpy_matrix(g).tolist()).replace(".0", "").replace("],", "\n")
        .replace("[", "").replace("]]", "").replace(" ", ""))
f.close()
