import networkx as nx
import matplotlib.pyplot as plt
import f as ff, star as ss, Path as p, h as hh, cycle as c, d as dd, w as ww

g = nx.Graph()
g.add_cycle([0, 1, 2])
g.add_edge(0, 3)
g.add_edge(1, 3)
g.add_edge(2, 3)

g_size = len(g.nodes)

# c.count_cycles(graph, cycle_size, graph_size)
c3 = c.count_cycles(g, 3, g_size)
c4 = c.count_cycles(g, 4, g_size)
c6 = c.count_cycles(g, 6, g_size)
c8 = c.count_cycles(g, 8, g_size)
# p.path_count(graph, maximum_path_length)
paths = p.path_count(g, 6)
# ff.count_f(graph, graph_size)
f = ff.count_f(g, g_size)
# hh.count_h(graph, graph_size)
h = hh.count_h(g, g_size)
# ss.count_star(graph, star_size)
s1_3 = ss.count_star(g, 3)
s1_4 = ss.count_star(g, 4)
# dd.count_d(graph, graph_size)
d = dd.count_d(g, g_size)
# ww.count_w(graph, graph_size)
w = ww.count_w(g, g_size)

print("C3: ", c3)
print("C4: ", c4)
print("C6: ", c6)
print("C8: ", c8)
print("Paths: ", paths)
print("F: ", f)
print("H: ", h)
print("S1,3: ", s1_3)
print("S1,4: ", s1_4)
print("D: ", d)
print("W: ", w)

nx.draw_networkx(g, with_labels=True, edge_color='red', node_color='blue', node_size=9)
plt.draw()
plt.show()
